const { getNext } = require('../../settings/services/sequence.service')

// Demo customer groups — codes are generated by the CGP sequence (CGP{####}).
const GROUPS = [
  { name: 'Retail',     description: 'Walk-in retail customers' },
  { name: 'Wholesale',  description: 'Bulk purchase accounts' },
  { name: 'VIP',        description: 'High-value accounts with premium pricing' },
  { name: 'Government', description: 'Government agencies and public institutions' },
]

module.exports = {
  name: 'customer-groups',
  tier: 'demo',
  order: 160,
  async run(ctx) {
    const { CustomerGroup } = ctx.models
    const organizationId = ctx.get('orgId')
    const createdBy = ctx.get('adminId')
    const rows = []
    for (const g of GROUPS) {
      // Check if already seeded by name (idempotent re-run).
      const existing = await CustomerGroup.findOne({ where: { name: g.name, organizationId } })
      if (existing) { rows.push(existing); continue }
      const code = await getNext('CGP', createdBy)
      const group = await CustomerGroup.create({
        ...g, code, status: 'active', organizationId, createdBy,
      })
      rows.push(group)
    }
    ctx.set('customerGroups', rows)
  },
}
