const { Router } = require('express')
const { authenticate } = require('../../middleware/auth')
const { requirePermission } = require('../../middleware/permission')
const { validate } = require('../../middleware/validate')
const controller = require('./billing.controller')
const { planRules, planUpdateRules, subscriptionRules } = require('./billing.validators')

const router = Router()
router.use(authenticate)
router.get('/plans', controller.listPlans)
router.get('/subscription', controller.mySubscription)
router.get('/invoices', controller.myInvoices)
router.post('/cancel', controller.cancel)
router.get('/admin/plans', requirePermission('billing.manage'), controller.adminListPlans)
router.post('/admin/plans', requirePermission('billing.manage'), planRules, validate, controller.adminCreatePlan)
router.get('/admin/plans/:id', requirePermission('billing.manage'), controller.adminGetPlan)
router.put('/admin/plans/:id', requirePermission('billing.manage'), planUpdateRules, validate, controller.adminUpdatePlan)
router.delete('/admin/plans/:id', requirePermission('billing.manage'), controller.adminDeletePlan)
router.get('/admin/subscriptions', requirePermission('billing.manage'), controller.adminListSubscriptions)
router.put('/admin/subscriptions/:organizationId', requirePermission('billing.manage'), subscriptionRules, validate, controller.adminSetSubscription)
module.exports = router
