const { Router } = require('express')
const { authenticate } = require('../../middleware/auth')
const { requirePermission } = require('../../middleware/permission')
const { validate } = require('../../middleware/validate')
const controller = require('./billing.controller')
const { planRules, planUpdateRules, subscriptionRules, subscribeRules } = require('./billing.validators')

const router = Router()
router.use(authenticate)
router.get('/plans', controller.listPlans)
router.get('/subscription', controller.mySubscription)
router.get('/invoices', controller.myInvoices)
// Tenant files a plan-change request; admin approve activates the plan.
router.post('/request', subscribeRules, validate, controller.requestPlanChange)
router.post('/cancel', controller.cancel)
router.get('/admin/plans', requirePermission('billing.manage'), controller.adminListPlans)
router.post('/admin/plans', requirePermission('billing.manage'), planRules, validate, controller.adminCreatePlan)
router.get('/admin/plans/:id', requirePermission('billing.manage'), controller.adminGetPlan)
router.put('/admin/plans/:id', requirePermission('billing.manage'), planUpdateRules, validate, controller.adminUpdatePlan)
router.delete('/admin/plans/:id', requirePermission('billing.manage'), controller.adminDeletePlan)
router.get('/admin/subscriptions', requirePermission('billing.manage'), controller.adminListSubscriptions)
router.get('/admin/subscriptions/:organizationId', requirePermission('billing.manage'), controller.adminGetSubscription)
router.put('/admin/subscriptions/:organizationId', requirePermission('billing.manage'), subscriptionRules, validate, controller.adminSetSubscription)
router.post('/admin/subscriptions/:organizationId/suspend', requirePermission('billing.manage'), controller.adminSuspendSubscription)
router.post('/admin/subscriptions/:organizationId/cancel', requirePermission('billing.manage'), controller.adminCancelSubscription)
router.get('/admin/plan-requests', requirePermission('billing.manage'), controller.adminListPlanRequests)
router.post('/admin/plan-requests/:id/approve', requirePermission('billing.manage'), controller.adminApprovePlanRequest)
router.post('/admin/plan-requests/:id/reject', requirePermission('billing.manage'), controller.adminRejectPlanRequest)
module.exports = router
